### PR TITLE
Added intitalViewDate support

### PR DESCRIPTION
**Pull request by robertprice**
This pull request adds support for an initialViewDate.

The latest version of the picker doesn't seem to support for showing week days, so I have commented this functionality out.

### CODE REVIEW

**Comment by jeuhen** [comment]
Hi Robert,

Thanks for your contribution, I will check it out.
The week numbers are indeed not supported by the library so unfortunately I had to made some changes to the library to get it working. So I will merge your functionality in the current version, such that week numbers will remain working.

Thanks again!

**Comment by robertprice** [comment]
Hi,

Thanks for the update.

We use the module for selecting start and end dates so my use case for the
change was making sure the end date opened at same month as the selected
start date.

It's good you've got the week number working, I was really stuck on that
one. It explains why I couldn't find any documentation on that. :-)

Cheers

Rob

**Comment by jeuhen** [comment]
Hi,

Thanks again for your contribution!
I merged your changes manually to make sure that the week numbers remain working. A new version has been published!

Cheers

Johan

**Comment by robertprice** [comment]
Thanks!

**Pull request closed without merging**
